### ISSUE TITLE
Unable to reproduce results from paper

### ISSUE THREAD

**Issue by FL33TW00D** [MRegina/DTW_for_fMRI#1]
Hi there,
I am attempting to reproduce the performance benefits you describe in your paper:
Resting state fMRI functional connectivity-based classification using convolutional neural network architecture.

I am using the same ANOVA F-Test Linear SVC described by Abraham et al with k=128 and C=0.05. However not only does DTW not provide the performance benefits stated in the paper (CORR 54.1 vs DTW 67.1), it performs worse than CORR. I can almost exactly match your results using CORR (54.1 cited in paper vs 54.6).

I am using the xnormalized_euclidean_45_unifiedOutput.txt files produced by this repo, after square rooting and dividing by 10e4 as requested.

Have I missed anything?

Many Thanks,
Christopher Fleetwood

**Comment by MRegina** [comment]
Hi Christopher,
I'm sorry I'm not checking this repository too frequently, could you
describe the issue in a bit more detail? or you did close the issue because
you found the solution?
Best,
Regina

Christopher Fleetwood ***@***.***> ezt írta (időpont: 2020.
júl. 27., H, 13:15):
