### ISSUE TITLE
New library implementing this functionality

### ISSUE THREAD

**Issue by FL33TW00D** [MRegina/DTW_for_fMRI#2]
Hi @MRegina,
I have implemented a library that performs the exact functionality from your paper, and can operate on numpy matricies directly using multithreaded Rust code. It should make your methods easier to use for fellow neuroimagers! It is available here: https://github.com/FL33TW00D/rustDTW

I've also written a blog post about the different kinds of timeseries similarity metrics for neuroimaging data, showing the benefits of DTW. You can find it here: https://www.fleetwood.dev/posts/fmri-timeseries-similarity

Try out the library and see if it is suitable!

Many Thanks,
Chris

**Comment by MRegina** [comment]
Hi Chris!
I'm glad to see the great results in your blogpost, I hope to see more and more people use DTW and similar methods to explore connectivity further,
Best,
Regina
